// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEG8RlZ7y0gfMCKJleaCiaJMbbjSseOVo',
    appId: '1:242030536834:web:ccc2bb8a68a56f62ecac9b',
    messagingSenderId: '242030536834',
    projectId: 'chessclan-a50f8',
    authDomain: 'chessclan-a50f8.firebaseapp.com',
    storageBucket: 'chessclan-a50f8.firebasestorage.app',
    measurementId: 'G-L76MJKFBHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1FJAINRig4QSV6b7kZaKjw1t8YQQgs18',
    appId: '1:242030536834:android:ee02a18107d1a569ecac9b',
    messagingSenderId: '242030536834',
    projectId: 'chessclan-a50f8',
    storageBucket: 'chessclan-a50f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEWop1bcqqL3MSEUIJMcnBO-mu2IUMAYI',
    appId: '1:242030536834:ios:935684106447ae7aecac9b',
    messagingSenderId: '242030536834',
    projectId: 'chessclan-a50f8',
    storageBucket: 'chessclan-a50f8.firebasestorage.app',
    iosBundleId: 'com.example.chessClanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEWop1bcqqL3MSEUIJMcnBO-mu2IUMAYI',
    appId: '1:242030536834:ios:935684106447ae7aecac9b',
    messagingSenderId: '242030536834',
    projectId: 'chessclan-a50f8',
    storageBucket: 'chessclan-a50f8.firebasestorage.app',
    iosBundleId: 'com.example.chessClanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEG8RlZ7y0gfMCKJleaCiaJMbbjSseOVo',
    appId: '1:242030536834:web:6246d4dd9d7eb5d8ecac9b',
    messagingSenderId: '242030536834',
    projectId: 'chessclan-a50f8',
    authDomain: 'chessclan-a50f8.firebaseapp.com',
    storageBucket: 'chessclan-a50f8.firebasestorage.app',
    measurementId: 'G-R7RYR46WHM',
  );
}
